// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTgS0UBFLfEMFCVlHnsCTS-IHlZSpiT0',
    appId: '1:515161087597:web:6be6dd83c77c5399bc6964',
    messagingSenderId: '515161087597',
    projectId: 'myrent-3d2a9',
    authDomain: 'myrent-3d2a9.firebaseapp.com',
    databaseURL: 'https://myrent-3d2a9-default-rtdb.firebaseio.com',
    storageBucket: 'myrent-3d2a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUTQRGGjpqqyptpTl5eHZPP_Pz_YariY8',
    appId: '1:515161087597:android:e825fbd19348cebabc6964',
    messagingSenderId: '515161087597',
    projectId: 'myrent-3d2a9',
    databaseURL: 'https://myrent-3d2a9-default-rtdb.firebaseio.com',
    storageBucket: 'myrent-3d2a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_PnByeg0wE_OZTGIttgzVI0aQCR4fRo4',
    appId: '1:515161087597:ios:9bfe8c9f8e7f5795bc6964',
    messagingSenderId: '515161087597',
    projectId: 'myrent-3d2a9',
    databaseURL: 'https://myrent-3d2a9-default-rtdb.firebaseio.com',
    storageBucket: 'myrent-3d2a9.firebasestorage.app',
    androidClientId: '515161087597-b8q7nv3963ic9lvd0a75q26g8tbq5ci7.apps.googleusercontent.com',
    iosClientId: '515161087597-2oetmhvgr2iniojuekelv2oau9ogtphd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_PnByeg0wE_OZTGIttgzVI0aQCR4fRo4',
    appId: '1:515161087597:ios:9bfe8c9f8e7f5795bc6964',
    messagingSenderId: '515161087597',
    projectId: 'myrent-3d2a9',
    databaseURL: 'https://myrent-3d2a9-default-rtdb.firebaseio.com',
    storageBucket: 'myrent-3d2a9.firebasestorage.app',
    androidClientId: '515161087597-b8q7nv3963ic9lvd0a75q26g8tbq5ci7.apps.googleusercontent.com',
    iosClientId: '515161087597-2oetmhvgr2iniojuekelv2oau9ogtphd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvTgS0UBFLfEMFCVlHnsCTS-IHlZSpiT0',
    appId: '1:515161087597:web:516a7c8faccf57a9bc6964',
    messagingSenderId: '515161087597',
    projectId: 'myrent-3d2a9',
    authDomain: 'myrent-3d2a9.firebaseapp.com',
    databaseURL: 'https://myrent-3d2a9-default-rtdb.firebaseio.com',
    storageBucket: 'myrent-3d2a9.firebasestorage.app',
  );
}
